FROM golang:1.23.5-alpine
WORKDIR /api
RUN go install github.com/air-verse/air@latest
RUN go install github.com/pressly/goose/v3/cmd/goose@latest
COPY go.mod go.sum cmd/api/main.go ./
RUN go mod tidy
COPY . .
EXPOSE 8080
CMD ["air"]
